version = 1

[[annotations]]
path = ["jungle_juice_(stereo).ogg", "apocalypse_(stereo).ogg", "somewhere_in_space_(stereo).ogg", "new_save_(stereo).ogg", "gruntwork_(stereo).ogg", "valley_(stereo).ogg", "8_oclock_ghosts_(stereo).ogg", "adventures_in_a_cardboard_box_(stereo).ogg", "crunked_up_(stereo).ogg"]
SPDX-FileCopyrightText = "Custom songs composed for Stellar Station by Darklyac."
SPDX-License-Identifier = "LicenseRef-Wallening"

[[annotations]]
path = ["the_void_beckons_(stereo).ogg", "bluespace_frogs_(stereo).ogg"]
SPDX-FileCopyrightText = "Custom songs composed for Stellar Station by Pigeonbeans."
SPDX-License-Identifier = "LicenseRef-Wallening"
